// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type UserDeleteReq struct {
	Phone    string `json:"phone"` // 根据手机号删除用户
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type UserDeleteResp struct {
}

type UserLoginReq struct {
	Phone    string `json:"phone"`
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}

type UserQueryReq struct {
	UserId int64 `form:"userId"`
}

type UserQueryResp struct {
	UserId    int64  `json:"userId"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	NickName  string `json:"nickName"`
	Avatar    string `json:"avatar"`
	Gender    string `json:"gender"`
	BirthDate int64  `json:"birthDate"`
	Role      string `json:"role"`
	Status    int64  `json:"status"`
}

type UserRegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type UserRegisterResp struct {
	UserId int64 `json:"userId"`
}

type UserUpdateReq struct {
	UserId    int64  `json:"userId"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	NickName  string `json:"nickName"`
	Avatar    string `json:"avatar"`
	Gender    string `json:"gender"`
	BirthDate int64  `json:"birthDate"`
	Role      string `json:"role"`
	Status    int64  `json:"status"`
}

type UserUpdateResp struct {
}
