// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"
	"time"

	Post "movieReviewSystem/movieReviewSystemApi/post/postApi/generateFileV1/internal/handler/Post"
	"movieReviewSystem/movieReviewSystemApi/post/postApi/generateFileV1/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Middleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/user/delete",
					Handler: Post.PostCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/query",
					Handler: Post.PostFindByPostIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/update",
					Handler: Post.PostDeleteByPostIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
