#!/usr/bin/env bash

# 打印当前目录
echo "Current directory: $(pwd)"

# 停止并清理 Docker Compose 服务
echo "Stopping Docker Compose services..."
docker-compose down
echo "Docker Compose services stopped and cleaned."

# 停止 etcd
echo "Stopping etcd..."
pkill etcd
echo "etcd stopped."

# 停止 user-rpc 和 user-api
echo "Stopping userRpc..."
pkill user-rpc
echo "userRpc stopped."

echo "Stopping userApi..."
pkill user-api
echo "userApi stopped."

# 清理日志文件（可选）
echo "Cleaning log files..."
rm -f etcd.log
echo "Log files cleaned."
cd movieReviewSystemApi/user/user-rpc/generateFileV1 || exit
rm -rf user-rpc user-rpc.log
cd ../../../../
cd movieReviewSystemApi/user/user-api/generateFileV1 || exit
rm -rf user-api user-api.log
cd ../../../../
echo "All services stopped and resources cleaned."