#!/usr/bin/env bash

# 打印当前目录
echo "Current directory: $(pwd)"

# 停止并清理 Docker Compose 服务
echo "Stopping Docker Compose services..."
docker-compose down
echo "Docker Compose services stopped and cleaned."

# 停止 etcd
echo "Stopping etcd..."
pkill etcd
echo "etcd stopped."

# 停止 userRpc 和 userApi
echo "Stopping userRpc..."
pkill userRpc
echo "userRpc stopped."

echo "Stopping userApi..."
pkill userApi
echo "userApi stopped."

# 清理日志文件（可选）
echo "Cleaning log files..."
rm -f etcd.log
echo "Log files cleaned."
cd movieReviewSystemApi/user/userRpc/generateFileV1 || exit
rm -rf userRpc userRpc.log
cd ../../../../
cd movieReviewSystemApi/user/userApi/generateFileV1 || exit
rm -rf userApi userApi.log
cd ../../../../
echo "All services stopped and resources cleaned."