// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: user.proto

package userservice

import (
	"context"

	"movieReviewSystem/movieReviewSystemApi/user/userRpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Relations               = __.Relations
	User                    = __.User
	UserDeleteReq           = __.UserDeleteReq
	UserDeleteResp          = __.UserDeleteResp
	UserLoginReq            = __.UserLoginReq
	UserLoginResp           = __.UserLoginResp
	UserQueryReq            = __.UserQueryReq
	UserQueryResp           = __.UserQueryResp
	UserRegisterReq         = __.UserRegisterReq
	UserRegisterResp        = __.UserRegisterResp
	UserRelationsGetReq     = __.UserRelationsGetReq
	UserRelationsGetResp    = __.UserRelationsGetResp
	UserRelationsUpdateReq  = __.UserRelationsUpdateReq
	UserRelationsUpdateResp = __.UserRelationsUpdateResp
	UserUpdateReq           = __.UserUpdateReq
	UserUpdateResp          = __.UserUpdateResp

	UserService interface {
		UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error)
		UserRegister(ctx context.Context, in *UserRegisterReq, opts ...grpc.CallOption) (*UserRegisterResp, error)
		UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error)
		UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error)
		UserQuery(ctx context.Context, in *UserQueryReq, opts ...grpc.CallOption) (*UserQueryResp, error)
		UserRelationsUpdate(ctx context.Context, in *UserRelationsUpdateReq, opts ...grpc.CallOption) (*UserRelationsUpdateResp, error)
		UserRelationsGet(ctx context.Context, in *UserRelationsGetReq, opts ...grpc.CallOption) (*UserRelationsGetResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}

func (m *defaultUserService) UserRegister(ctx context.Context, in *UserRegisterReq, opts ...grpc.CallOption) (*UserRegisterResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.UserRegister(ctx, in, opts...)
}

func (m *defaultUserService) UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.UserDelete(ctx, in, opts...)
}

func (m *defaultUserService) UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.UserUpdate(ctx, in, opts...)
}

func (m *defaultUserService) UserQuery(ctx context.Context, in *UserQueryReq, opts ...grpc.CallOption) (*UserQueryResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.UserQuery(ctx, in, opts...)
}

func (m *defaultUserService) UserRelationsUpdate(ctx context.Context, in *UserRelationsUpdateReq, opts ...grpc.CallOption) (*UserRelationsUpdateResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.UserRelationsUpdate(ctx, in, opts...)
}

func (m *defaultUserService) UserRelationsGet(ctx context.Context, in *UserRelationsGetReq, opts ...grpc.CallOption) (*UserRelationsGetResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.UserRelationsGet(ctx, in, opts...)
}
