// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type GroupAdminIdReq struct {
	UserId  int64 `json:"userId"`
	AdminId int64 `json:"addUserId"`
	GroupId int64 `json:"groupId"`
	Status  int64 `json:"status"`
}

type GroupAdminIdResp struct {
}

type GroupCreateReq struct {
	GroupName  string `json:"groupName"`
	GroupUrl   string `json:"groupUrl"`
	RootUserId int64  `json:"rootUserId"`
}

type GroupCreateResp struct {
	GroupId int64 `json:"groupId"`
}

type GroupDeleteReq struct {
	UserId  int64 `json:"userId"`
	GroupId int64 `json:"groupId"`
	Status  int64 `json:"status"`
}

type GroupDeleteResp struct {
}

type GroupUserIdReq struct {
	UserId    int64 `json:"userId"`
	AddUserId int64 `json:"addUserId"`
	GroupId   int64 `json:"groupId"`
	Status    int64 `json:"status"`
}

type GroupUserIdResp struct {
}
