// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
)

type userRelationsModel interface {
	Insert(ctx context.Context, data *UserRelations) error
	FindOne(ctx context.Context, id int64) (*UserRelations, error)
	Update(ctx context.Context, data *UserRelations) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id int64) (int64, error)
}

type defaultUserRelationsModel struct {
	conn *mon.Model
}

func newDefaultUserRelationsModel(conn *mon.Model) *defaultUserRelationsModel {
	return &defaultUserRelationsModel{conn: conn}
}

func (m *defaultUserRelationsModel) Insert(ctx context.Context, data *UserRelations) error {
	data.CreateAt = time.Now().Unix()
	data.UpdateAt = time.Now().Unix()

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultUserRelationsModel) FindOne(ctx context.Context, id int64) (*UserRelations, error) {
	var data UserRelations

	err := m.conn.FindOne(ctx, &data, bson.M{"_id": id})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRelationsModel) Update(ctx context.Context, data *UserRelations) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now().Unix()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultUserRelationsModel) Delete(ctx context.Context, id int64) (int64, error) {

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": id})
	return res, err
}
