// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type userRealtiosnModel interface {
	Insert(ctx context.Context, data *UserRealtiosn) error
	FindOne(ctx context.Context, id string) (*UserRealtiosn, error)
	Update(ctx context.Context, data *UserRealtiosn) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultUserRealtiosnModel struct {
	conn *mon.Model
}

func newDefaultUserRealtiosnModel(conn *mon.Model) *defaultUserRealtiosnModel {
	return &defaultUserRealtiosnModel{conn: conn}
}

func (m *defaultUserRealtiosnModel) Insert(ctx context.Context, data *UserRealtiosn) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now().Unix()
		data.UpdateAt = time.Now().Unix()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultUserRealtiosnModel) FindOne(ctx context.Context, id string) (*UserRealtiosn, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data UserRealtiosn

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRealtiosnModel) Update(ctx context.Context, data *UserRealtiosn) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now().Unix()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultUserRealtiosnModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}
