// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type Message struct {
	GroupId    int64  `json:"groupId"`
	MessageId  int64  `json:"messageId"`
	FromUserId int64  `json:"fromUserId"`
	ToUserId   int64  `json:"toUserId"`
	Text       string `json:"text"`
	CreateDate int64  `json:"createDate"`
}

type MessageClientReq struct {
	UserId int64 `form:"userId"`
}

type MessageReciveReq struct {
	MessageId int64 `json:"messageId"`
	UserId    int64 `json:"userId"`
	Limit     int64 `json:"limit"`
}

type MessageReciveResp struct {
	Message map[int64][]Message `json:"message"`
}
