// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.19.4
// source: thumbup.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThumbUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThumbUpId     int64                  `protobuf:"varint,1,opt,name=ThumbUpId,proto3" json:"ThumbUpId,omitempty"`
	BaseId        int64                  `protobuf:"varint,2,opt,name=BaseId,proto3" json:"BaseId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreateAt      int64                  `protobuf:"varint,4,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,5,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
	Val           int64                  `protobuf:"varint,6,opt,name=Val,proto3" json:"Val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUp) Reset() {
	*x = ThumbUp{}
	mi := &file_thumbup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUp) ProtoMessage() {}

func (x *ThumbUp) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUp.ProtoReflect.Descriptor instead.
func (*ThumbUp) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{0}
}

func (x *ThumbUp) GetThumbUpId() int64 {
	if x != nil {
		return x.ThumbUpId
	}
	return 0
}

func (x *ThumbUp) GetBaseId() int64 {
	if x != nil {
		return x.BaseId
	}
	return 0
}

func (x *ThumbUp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ThumbUp) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *ThumbUp) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *ThumbUp) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

// 获取点赞信息
type ThumbUpGetRespStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThumbUp       []*ThumbUp             `protobuf:"bytes,1,rep,name=ThumbUp,proto3" json:"ThumbUp,omitempty"` //点赞信息表
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`    //总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpGetRespStruct) Reset() {
	*x = ThumbUpGetRespStruct{}
	mi := &file_thumbup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpGetRespStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpGetRespStruct) ProtoMessage() {}

func (x *ThumbUpGetRespStruct) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpGetRespStruct.ProtoReflect.Descriptor instead.
func (*ThumbUpGetRespStruct) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{1}
}

func (x *ThumbUpGetRespStruct) GetThumbUp() []*ThumbUp {
	if x != nil {
		return x.ThumbUp
	}
	return nil
}

func (x *ThumbUpGetRespStruct) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ThumbUpGetByBaseIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseId        []int64                `protobuf:"varint,1,rep,packed,name=BaseId,proto3" json:"BaseId,omitempty"`
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpGetByBaseIdReq) Reset() {
	*x = ThumbUpGetByBaseIdReq{}
	mi := &file_thumbup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpGetByBaseIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpGetByBaseIdReq) ProtoMessage() {}

func (x *ThumbUpGetByBaseIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpGetByBaseIdReq.ProtoReflect.Descriptor instead.
func (*ThumbUpGetByBaseIdReq) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{2}
}

func (x *ThumbUpGetByBaseIdReq) GetBaseId() []int64 {
	if x != nil {
		return x.BaseId
	}
	return nil
}

func (x *ThumbUpGetByBaseIdReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ThumbUpGetByUserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []int64                `protobuf:"varint,1,rep,packed,name=UserId,proto3" json:"UserId,omitempty"`
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpGetByUserIdReq) Reset() {
	*x = ThumbUpGetByUserIdReq{}
	mi := &file_thumbup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpGetByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpGetByUserIdReq) ProtoMessage() {}

func (x *ThumbUpGetByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpGetByUserIdReq.ProtoReflect.Descriptor instead.
func (*ThumbUpGetByUserIdReq) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{3}
}

func (x *ThumbUpGetByUserIdReq) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *ThumbUpGetByUserIdReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ThumbUpGetByThumbUpIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThumbUpId     []int64                `protobuf:"varint,1,rep,packed,name=ThumbUpId,proto3" json:"ThumbUpId,omitempty"`
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpGetByThumbUpIdReq) Reset() {
	*x = ThumbUpGetByThumbUpIdReq{}
	mi := &file_thumbup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpGetByThumbUpIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpGetByThumbUpIdReq) ProtoMessage() {}

func (x *ThumbUpGetByThumbUpIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpGetByThumbUpIdReq.ProtoReflect.Descriptor instead.
func (*ThumbUpGetByThumbUpIdReq) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{4}
}

func (x *ThumbUpGetByThumbUpIdReq) GetThumbUpId() []int64 {
	if x != nil {
		return x.ThumbUpId
	}
	return nil
}

func (x *ThumbUpGetByThumbUpIdReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ThumbUpGetResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ThumbUps      []*ThumbUpGetRespStruct `protobuf:"bytes,1,rep,name=ThumbUps,proto3" json:"ThumbUps,omitempty"`
	Count         int64                   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpGetResp) Reset() {
	*x = ThumbUpGetResp{}
	mi := &file_thumbup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpGetResp) ProtoMessage() {}

func (x *ThumbUpGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpGetResp.ProtoReflect.Descriptor instead.
func (*ThumbUpGetResp) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{5}
}

func (x *ThumbUpGetResp) GetThumbUps() []*ThumbUpGetRespStruct {
	if x != nil {
		return x.ThumbUps
	}
	return nil
}

func (x *ThumbUpGetResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 创建修改点赞点踩信息
type ThumbUpCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseId        int64                  `protobuf:"varint,1,opt,name=BaseId,proto3" json:"BaseId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Type          int64                  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Val           int64                  `protobuf:"varint,4,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpCreateReq) Reset() {
	*x = ThumbUpCreateReq{}
	mi := &file_thumbup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpCreateReq) ProtoMessage() {}

func (x *ThumbUpCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpCreateReq.ProtoReflect.Descriptor instead.
func (*ThumbUpCreateReq) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{6}
}

func (x *ThumbUpCreateReq) GetBaseId() int64 {
	if x != nil {
		return x.BaseId
	}
	return 0
}

func (x *ThumbUpCreateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ThumbUpCreateReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ThumbUpCreateReq) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type ThumbUpCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpCreateResp) Reset() {
	*x = ThumbUpCreateResp{}
	mi := &file_thumbup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpCreateResp) ProtoMessage() {}

func (x *ThumbUpCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_thumbup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpCreateResp.ProtoReflect.Descriptor instead.
func (*ThumbUpCreateResp) Descriptor() ([]byte, []int) {
	return file_thumbup_proto_rawDescGZIP(), []int{7}
}

var File_thumbup_proto protoreflect.FileDescriptor

var file_thumbup_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x22, 0xa1, 0x01, 0x0a, 0x07, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x55, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x22, 0x58, 0x0a, 0x14,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x2e,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x52, 0x07, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x15, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55,
	0x70, 0x47, 0x65, 0x74, 0x42, 0x79, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x43, 0x0a, 0x15, 0x54,
	0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x4c, 0x0a, 0x18, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x09, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x61,
	0x0a, 0x0e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x39, 0x0a, 0x08, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x2e, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x08, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x68, 0x0a, 0x10, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x13, 0x0a, 0x11, 0x54,
	0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x32, 0xcb, 0x02, 0x0a, 0x0e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x74, 0x68, 0x75, 0x6d,
	0x62, 0x55, 0x70, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x74, 0x68, 0x75, 0x6d,
	0x62, 0x55, 0x70, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x4d, 0x0a, 0x12, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x55, 0x70, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x55, 0x70, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x53, 0x0a, 0x15, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x49, 0x64, 0x12, 0x21, 0x2e, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x55, 0x70, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0d, 0x54, 0x68, 0x75, 0x6d, 0x70, 0x55,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x55,
	0x70, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x70, 0x2e, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x55, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thumbup_proto_rawDescOnce sync.Once
	file_thumbup_proto_rawDescData = file_thumbup_proto_rawDesc
)

func file_thumbup_proto_rawDescGZIP() []byte {
	file_thumbup_proto_rawDescOnce.Do(func() {
		file_thumbup_proto_rawDescData = protoimpl.X.CompressGZIP(file_thumbup_proto_rawDescData)
	})
	return file_thumbup_proto_rawDescData
}

var file_thumbup_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_thumbup_proto_goTypes = []any{
	(*ThumbUp)(nil),                  // 0: thumbUp.ThumbUp
	(*ThumbUpGetRespStruct)(nil),     // 1: thumbUp.ThumbUpGetRespStruct
	(*ThumbUpGetByBaseIdReq)(nil),    // 2: thumbUp.ThumbUpGetByBaseIdReq
	(*ThumbUpGetByUserIdReq)(nil),    // 3: thumbUp.ThumbUpGetByUserIdReq
	(*ThumbUpGetByThumbUpIdReq)(nil), // 4: thumbUp.ThumbUpGetByThumbUpIdReq
	(*ThumbUpGetResp)(nil),           // 5: thumbUp.ThumbUpGetResp
	(*ThumbUpCreateReq)(nil),         // 6: thumbUp.ThumbUpCreateReq
	(*ThumbUpCreateResp)(nil),        // 7: thumbUp.ThumbUpCreateResp
}
var file_thumbup_proto_depIdxs = []int32{
	0, // 0: thumbUp.ThumbUpGetRespStruct.ThumbUp:type_name -> thumbUp.ThumbUp
	1, // 1: thumbUp.ThumbUpGetResp.ThumbUps:type_name -> thumbUp.ThumbUpGetRespStruct
	2, // 2: thumbUp.ThumbUpService.ThumbUpGetByBaseId:input_type -> thumbUp.ThumbUpGetByBaseIdReq
	3, // 3: thumbUp.ThumbUpService.ThumbUpGetByUserId:input_type -> thumbUp.ThumbUpGetByUserIdReq
	4, // 4: thumbUp.ThumbUpService.ThumbUpGetByThumbUpId:input_type -> thumbUp.ThumbUpGetByThumbUpIdReq
	6, // 5: thumbUp.ThumbUpService.ThumpUpCreate:input_type -> thumbUp.ThumbUpCreateReq
	5, // 6: thumbUp.ThumbUpService.ThumbUpGetByBaseId:output_type -> thumbUp.ThumbUpGetResp
	5, // 7: thumbUp.ThumbUpService.ThumbUpGetByUserId:output_type -> thumbUp.ThumbUpGetResp
	5, // 8: thumbUp.ThumbUpService.ThumbUpGetByThumbUpId:output_type -> thumbUp.ThumbUpGetResp
	7, // 9: thumbUp.ThumbUpService.ThumpUpCreate:output_type -> thumbUp.ThumbUpCreateResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_thumbup_proto_init() }
func file_thumbup_proto_init() {
	if File_thumbup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thumbup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thumbup_proto_goTypes,
		DependencyIndexes: file_thumbup_proto_depIdxs,
		MessageInfos:      file_thumbup_proto_msgTypes,
	}.Build()
	File_thumbup_proto = out.File
	file_thumbup_proto_rawDesc = nil
	file_thumbup_proto_goTypes = nil
	file_thumbup_proto_depIdxs = nil
}
