// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: thumbup.proto

package server

import (
	"context"

	"movieReviewSystem/movieReviewSystemApi/thumbup/thumbupRpc/generateFileV1/internal/logic"
	"movieReviewSystem/movieReviewSystemApi/thumbup/thumbupRpc/generateFileV1/internal/svc"
	"movieReviewSystem/movieReviewSystemApi/thumbup/thumbupRpc/pb"
)

type ThumbUpServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedThumbUpServiceServer
}

func NewThumbUpServiceServer(svcCtx *svc.ServiceContext) *ThumbUpServiceServer {
	return &ThumbUpServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ThumbUpServiceServer) ThumbUpGetByBaseId(ctx context.Context, in *__.ThumbUpGetByBaseIdReq) (*__.ThumbUpGetResp, error) {
	l := logic.NewThumbUpGetByBaseIdLogic(ctx, s.svcCtx)
	return l.ThumbUpGetByBaseId(in)
}

func (s *ThumbUpServiceServer) ThumbUpGetByUserId(ctx context.Context, in *__.ThumbUpGetByUserIdReq) (*__.ThumbUpGetResp, error) {
	l := logic.NewThumbUpGetByUserIdLogic(ctx, s.svcCtx)
	return l.ThumbUpGetByUserId(in)
}

func (s *ThumbUpServiceServer) ThumbUpGetByThumbUpId(ctx context.Context, in *__.ThumbUpGetByThumbUpIdReq) (*__.ThumbUpGetResp, error) {
	l := logic.NewThumbUpGetByThumbUpIdLogic(ctx, s.svcCtx)
	return l.ThumbUpGetByThumbUpId(in)
}

func (s *ThumbUpServiceServer) ThumpUpCreate(ctx context.Context, in *__.ThumbUpCreateReq) (*__.ThumbUpCreateResp, error) {
	l := logic.NewThumpUpCreateLogic(ctx, s.svcCtx)
	return l.ThumpUpCreate(in)
}
