// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type Relations struct {
	RelationsId      int64 `json:"relationsId"`
	UserId           int64 `json:"userId"`
	OtherId          int64 `json:"otherId"`
	RelationshipType int64 `json:"relationshipType"`
	CreateAt         int64 `json:"createAt"`
	UpdateAt         int64 `json:"updateAt"`
}

type User struct {
	UserId    int64  `json:"userId"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	NickName  string `json:"nickName"`
	Avatar    string `json:"avatar"`
	Gender    int64  `json:"gender"`
	BirthDate int64  `json:"birthDate"`
	Role      string `json:"role"`
	Status    int64  `json:"status"`
	CreateAt  int64  `json:"createAt"`
	UpdateAt  int64  `json:"updateAt"`
}

type UserDeleteReq struct {
	Phone    string `json:"phone"` // 根据手机号删除用户
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type UserDeleteResp struct {
	User User `json:"user"`
}

type UserLoginReq struct {
	Phone    string `json:"phone"`
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}

type UserQueryReq struct {
	UserId int64 `json"userId"`
}

type UserQueryResp struct {
	User User `json:"user"`
}

type UserRegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type UserRegisterResp struct {
	User User `json:"user"`
}

type UserRelationsGetReq struct {
	UserId  int64 `json:"userId"`
	OUserId int64 `json:"oUserId"`
}

type UserRelationsGetResp struct {
	Relations Relations `json:"relations"`
}

type UserRelationsUpdateReq struct {
	UserId           int64 `json:"userId"`
	OUserId          int64 `json:"oUserId"`
	RelationshipType int64 `json:"relations"`
}

type UserRelationsUpdateResp struct {
	Relations Relations `json:"relations"`
}

type UserUpdateReq struct {
	User User `json:"user"`
}

type UserUpdateResp struct {
	User User `json:"user"`
}
