// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
)

type reviewModel interface {
	Insert(ctx context.Context, data *Review) error
	FindOne(ctx context.Context, id int64) (*Review, error)
	Update(ctx context.Context, data *Review) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id int64) (int64, error)
}

type defaultReviewModel struct {
	conn *mon.Model
}

func newDefaultReviewModel(conn *mon.Model) *defaultReviewModel {
	return &defaultReviewModel{conn: conn}
}

func (m *defaultReviewModel) Insert(ctx context.Context, data *Review) error {
	data.CreateAt = time.Now().Unix()
	data.UpdateAt = time.Now().Unix()

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultReviewModel) FindOne(ctx context.Context, id int64) (*Review, error) {
	var data Review

	err := m.conn.FindOne(ctx, &data, bson.M{"_id": id})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReviewModel) Update(ctx context.Context, data *Review) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now().Unix()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultReviewModel) Delete(ctx context.Context, id int64) (int64, error) {

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": id})
	return res, err
}
