// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: group.proto

package server

import (
	"context"

	"movieReviewSystem/movieReviewSystemApi/group/groupRpc/generateFileV1/internal/logic"
	"movieReviewSystem/movieReviewSystemApi/group/groupRpc/generateFileV1/internal/svc"
	"movieReviewSystem/movieReviewSystemApi/group/groupRpc/pb"
)

type GroupServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedGroupServiceServer
}

func NewGroupServiceServer(svcCtx *svc.ServiceContext) *GroupServiceServer {
	return &GroupServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServiceServer) GroupCreate(ctx context.Context, in *__.GroupCreateReq) (*__.GroupCreateResp, error) {
	l := logic.NewGroupCreateLogic(ctx, s.svcCtx)
	return l.GroupCreate(in)
}

func (s *GroupServiceServer) GroupUserId(ctx context.Context, in *__.GroupUserIdReq) (*__.GroupUserIdResp, error) {
	l := logic.NewGroupUserIdLogic(ctx, s.svcCtx)
	return l.GroupUserId(in)
}

func (s *GroupServiceServer) GroupAdminId(ctx context.Context, in *__.GroupAdminIdReq) (*__.GroupAdminIdResp, error) {
	l := logic.NewGroupAdminIdLogic(ctx, s.svcCtx)
	return l.GroupAdminId(in)
}

func (s *GroupServiceServer) GroupDelete(ctx context.Context, in *__.GroupDeleteReq) (*__.GroupDeleteResp, error) {
	l := logic.NewGroupDeleteLogic(ctx, s.svcCtx)
	return l.GroupDelete(in)
}
