// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: post.proto

package server

import (
	"context"

	"movieReviewSystem/movieReviewSystemApi/post/postRpc/generateFileV1/internal/logic"
	"movieReviewSystem/movieReviewSystemApi/post/postRpc/generateFileV1/internal/svc"
	"movieReviewSystem/movieReviewSystemApi/post/postRpc/pb"
)

type PostServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedPostServiceServer
}

func NewPostServiceServer(svcCtx *svc.ServiceContext) *PostServiceServer {
	return &PostServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServiceServer) PostCreate(ctx context.Context, in *__.PostCreateReq) (*__.PostCreateResp, error) {
	l := logic.NewPostCreateLogic(ctx, s.svcCtx)
	return l.PostCreate(in)
}

func (s *PostServiceServer) PostFindByPostId(ctx context.Context, in *__.PostFindByPostIdReq) (*__.PostFindResp, error) {
	l := logic.NewPostFindByPostIdLogic(ctx, s.svcCtx)
	return l.PostFindByPostId(in)
}

func (s *PostServiceServer) PostDeleteByUserId(ctx context.Context, in *__.PostDeleteByUserIdReq) (*__.PostDeleteResp, error) {
	l := logic.NewPostDeleteByUserIdLogic(ctx, s.svcCtx)
	return l.PostDeleteByUserId(in)
}
