// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type PostCreateReq struct {
	UserId  int64    `json:"userId"`
	ThemeId int64    `json:"themeId"`
	Title   string   `json:"title"`
	Text    string   `json:"text"`
	Image   []string `json:"image"`
	Video   []string `json:"video"`
	Source  int64    `json:"source"`
}

type PostCreateResp struct {
	PostId int64 `json:"postId"`
}

type PostDeleteByPostIdReq struct {
	PostId int64 `json:"postId"`
}

type PostDeleteResp struct {
}

type PostFindByPostIdReq struct {
	PostId int64 `from:"postId"`
}

type PostFindResp struct {
	PostId int64    `json:"postId"`
	Text   string   `json:"text"`
	Image  []string `json:"image"`
	Video  []string `json:"video"`
	UserId int64    `json:"userId"`
}

type PostGetListRep struct {
	UserId int64 `form:"userId"`
	Sort   int64 `form:"sort"`
	Offset int64 `form:"offset"`
	Limit  int64 `form:"limit"`
}

type PostGetListResp struct {
	PostInfos []Post `json:"postInfos"`
}
