// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type PostCreateReq struct {
	Text  string   `json:"text"`
	Image []string `json:"image"`
	Video []string `json:"video"`
}

type PostCreateResp struct {
	PostId int64 `json:"postId"`
}

type PostDeleteByPostIdReq struct {
	PostId int64 `json:"postId"`
}

type PostDeleteResp struct {
}

type PostFindByPostIdReq struct {
	PostId int64 `from:"postId"`
}

type PostFindResp struct {
	PostId int64    `json:"postId"`
	Text   string   `json:"text"`
	Image  []string `json:"image"`
	Video  []string `json:"video"`
	UserId int64    `json:"userId"`
}
