// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Post struct {
	UserId     int64    `json:"userId"`
	ThemeId    int64    `json:"themeId"`
	Title      string   `json:"title"`
	Text       string   `json:"text"`
	Image      []string `json:"image"`
	Video      []string `json:"video"`
	CreateTime int64    `json:"createTime"`
	UpdateTime int64    `json:"updateTime"`
	Source     int64    `json:"source"`
}
