// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: user.proto

package server

import (
	"context"

	"movieReviewSystem/movieReviewSystemApi/user/userRpc/generateFileV1/internal/logic"
	"movieReviewSystem/movieReviewSystemApi/user/userRpc/generateFileV1/internal/svc"
	"movieReviewSystem/movieReviewSystemApi/user/userRpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) UserLogin(ctx context.Context, in *__.UserLoginReq) (*__.UserLoginResp, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}

func (s *UserServiceServer) UserRegister(ctx context.Context, in *__.UserRegisterReq) (*__.UserRegisterResp, error) {
	l := logic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}

func (s *UserServiceServer) UserDelete(ctx context.Context, in *__.UserDeleteReq) (*__.UserDeleteResp, error) {
	l := logic.NewUserDeleteLogic(ctx, s.svcCtx)
	return l.UserDelete(in)
}

func (s *UserServiceServer) UserUpdate(ctx context.Context, in *__.UserUpdateReq) (*__.UserUpdateResp, error) {
	l := logic.NewUserUpdateLogic(ctx, s.svcCtx)
	return l.UserUpdate(in)
}

func (s *UserServiceServer) UserQuery(ctx context.Context, in *__.UserQueryReq) (*__.UserQueryResp, error) {
	l := logic.NewUserQueryLogic(ctx, s.svcCtx)
	return l.UserQuery(in)
}

func (s *UserServiceServer) UserRelationsUpdate(ctx context.Context, in *__.UserRelationsUpdateReq) (*__.UserRelationsUpdateResp, error) {
	l := logic.NewUserRelationsUpdateLogic(ctx, s.svcCtx)
	return l.UserRelationsUpdate(in)
}

func (s *UserServiceServer) UserRelationsGet(ctx context.Context, in *__.UserRelationsGetReq) (*__.UserRelationsGetResp, error) {
	l := logic.NewUserRelationsGetLogic(ctx, s.svcCtx)
	return l.UserRelationsGet(in)
}
